### PR TITLE
Added GitHub CI action to check build on PRs and pushes

### PR DESCRIPTION
**Pull request by m1el**
Based on PR #13 by @evanrichter, but now implements a strict check for warnings.

See example fail message: https://github.com/m1el/chocolate_milk/runs/625640403

See example PR that has a failed build: https://github.com/m1el/chocolate_milk/pull/1

URLs to workflow badge:
- https://github.com/m1el/chocolate_milk/workflows/Build/badge.svg
- https://github.com/gamozolabs/chocolate_milk/workflows/Build/badge.svg (after this PR gets merged)

### CODE REVIEW

**Comment by shirshak55** [comment]
adding windows support may be good too because in stream he was saying it should run fine on window :D

**Comment by evanrichter** [comment]
@m1el I also considered changing the calls to cargo in main.rs, but that will seriously impact development speed in my opinion. Doing it this way will not only impact the CI, but also the live development.

I think a better approach would be a patch file with these changes applied to main.rs only during the CI build.

**Comment by m1el** [comment]
@evanrichter this creates a separate flag for `chocolate_milk` that checks for warnings.  It doesn't affect the regular development flow (`cargo run`) at all.

**Comment by evanrichter** [comment]
oh I see it now :) I like it.

**Comment by gamozolabs** [comment]
Looks awesome, thank you, merged.

**Pull request merged**
