### PR TITLE
Fix path to configure in SNAPSHOTTING.md

### PR DESCRIPTION
**Pull request by palleiko**

### CODE REVIEW

**Comment by gamozolabs** [comment]
Perhaps I'm missing something here but it seems to work as I mention according to the "get QEMU" and "build QEMU" sections. (I recognize the docs suck right now, sorry about that)

```
pleb@gamey:~$ mkdir test
pleb@gamey:~$ cd test
pleb@gamey:~/test$ git clone https://github.com/qemu/QEMU
Cloning into 'QEMU'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 487844 (delta 0), reused 2 (delta 0), pack-reused 487840
Receiving objects: 100% (487844/487844), 261.36 MiB | 55.63 MiB/s, done.
Resolving deltas: 100% (394597/394597), done.
pleb@gamey:~/test$ mkdir build
pleb@gamey:~/test$ cd build
pleb@gamey:~/test/build$ ../QEMU/configure --target-list=x86_64-softmmu
Install prefix    /usr/local
BIOS directory    /usr/local/share/qemu
firmware path     /usr/local/share/qemu-firmware
binary directory  /usr/local/bin
library directory /usr/local/lib
```

**Comment by palleiko** [comment]
Oops, that's correct. Sorry about that! I was being a fool.

**Comment by gamozolabs** [comment]
No problem. Are you trying this out? Any success? I haven't really "released" it yet, so I'd be so excited to hear it's working on someone else's machine with this little docs!

**Comment by palleiko** [comment]
It's all built but I haven't tested anything yet. Looking very promising for a target I'm attempting to fuzz

**Pull request closed without merging**
