### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by gamozolabs** [comment]
This is your second rejected PR to format the code. I highly recommend finding other ways to contribute to projects than mass tool-automated format requests.

**Comment by evanrichter** [comment]
that's annoying. this user's entire account history is this same stuff. reported to github as it really shouldn't be allowed

**Comment by Atul9** [comment]
sorry, I didn't check the closed PR.

**Comment by Atul9** [comment]
@gamozolabs @evanrichter sorry, I didn't check the closed PR.

**Pull request closed without merging**
